# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muxy < Formula
  desc "Proxy for simulating real-world distributed system failures to improve resilience in your applications."
  homepage "https://github.com/asjdf/muxy"
  version "1.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/asjdf/muxy/releases/download/v1.0.0/muxy_Darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "530407935d6a86de5273e78420f289c645b3186941865a120cc8de1d7a8c5bbe"

    def install
      bin.install "muxy"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asjdf/muxy/releases/download/v1.0.0/muxy_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c027a7fe980fbd92919aa182105e3a82a27a7f7cb40dbae62fb1e1203da47245"

      def install
        bin.install "muxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/asjdf/muxy/releases/download/v1.0.0/muxy_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "def25a8c13900bfa96afd46c0ee7a73830f38be4e84d8ab948a6e8d0183a9824"

      def install
        bin.install "muxy"
      end
    end
  end

  def caveats
    <<~EOS
      Check https://github.com/asjdf/muxy
    EOS
  end
end
